OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/climate/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r0  --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/climate/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r1 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/climate/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r2 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/guncontrol/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r0 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/guncontrol/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r1 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/guncontrol/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r2 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/immigration/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r0 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/immigration/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r1 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/immigration/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r2 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/samesex/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r0 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/samesex/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r1 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/samesex/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r2 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/smoking/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r0 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/smoking/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r1 --objective calibration
OMP_NUM_THREADS=4 python -m core.experiments.combo projects/mfc/smoking/ framing year_group config/doc2vec_test.json --label Health --model MLP -t 0.9 --n_calib 100 --penalty l2 --suffix _r2 --objective calibration

